openapi: 3.0.3
info:
  title: Use Case 3 - API
  description: |-
    ### WIP: This document is a work in progress. The API documented here is subject to change and should not be widely adopted yet.
    This document describes the public API implemented by theaters to provide their current repertoire.

    This document is intended as documentation for consumers of the API *as well as* anyone who intends to implement an API endpoint that is compatible with Use Case 3. 

    ### Notes for API implementors

    * It's not required to use the same endpoint name as documented here. The important part is to implement a single endpoint that returns data in the format declared in this specification.
    * You can test whether your implementation matches this specification using our custom [validation page](validate)
  # termsOfService: http://swagger.io/terms/
  contact:
    email: retzlaff@buehnenverein.de
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
# servers:
#   - url: https://petstore3.swagger.io/api/v3
tags:
  - name: events
    description: Endpoint providing public information about upcoming events
paths:
  /events:
    get:
      tags:
        - events
      summary: Provides public information about events
      description: "TODO: Write description"
      operationId: getEvents
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repertoire"
components:
  schemas:
    Repertoire:
      required:
        - name
        - productions
        - version
      additionalProperties: false
      type: object
      properties:
        version:
          type: string
          description: The API version that is being used. MUST be the string "v1" for now.
          enum:
            - v1
        name:
          type: string
          description: "The organization's name"
          example: "Staatstheater Augsburg"
        address:
          type: object
          additionalProperties: false
          properties:
            postalCode:
              type: string
              # pattern: "\d{5}"
              example: 86153
            streetAddress:
              type: string
              example: Provinostr. 52
            city:
              type: string
              example: Augsburg
        productions:
          type: array
          description: "The collection of all productions in the repertoire. The value must be an object that maps from a unique production ID to a `Production` object describing the production."
          items:
            $ref: "#/components/schemas/Production"

    Production:
      type: object
      description: "An object containing unchanging information about the production."
      additionalProperties: false
      required:
        - title
        - events
      properties:
        title:
          type: string
          description: The event title
          example: Hedwig and the Angry Inch
        subtitle:
          type: string
          description: The event's optional subtitle
          example: US-amerikanisches Off-Broadway-Rock-Musical
        description:
          type: string
          description: A text describing the production
          example: Hedwig, die Queen des Glamrock, kommt auf ihrer Tournee in Augsburg vorbei! Gemeinsam mit ihrer Band The Angry Inch gibt sie eines ihrer mitreißenden Konzerte. Zwischen den Songs, die – mal Rocknummer, mal Country-Ballade – von ihrem Leben und der Suche nach der eigenen Identität erzählen, kommt sie dem Publikum so nah wie nie.\nDiese Show sollten Sie nicht verpassen!
        teaser:
          type: string
          description: A short text describing the production
          example: "Das Kult-Rockmusical »Hedwig and the Angry Inch« wurde innerhalb weniger Jahre vom Off-Broadway-Geheimtipp zu einem Hit am Broadway selbst. 2023 erobert Hedwig, die »weltweit ignorierte Queen of Glamrock« endlich auch die Herzen des Augsburger Publikums – mit dem langjährigen Schauspiel-Ensemble-Mitglied Thomas Prazak in der Hauptrolle. Die Live-Musik steuern Stefan Leibold, Jonas Horche, Tilman Herpichböhm und Niklas Rehle als Band »The Angry Inch« bei."
        additionalInfo:
          type: string
          description: Additional information about the production
        events:
          type: array
          description: "List of current events offered by the organization"
          items:
            $ref: "#/components/schemas/Event"
        branch:
          type: string
          description: The branch of theatre this production belongs to, e.g. "Schauspiel", "Musiktheater", "Oper", etc.
          example: "Musiktheater"
        genre:
          type: string
          description: The genre of this production.
          example: "Rock-Musical"
        accessibility:
          $ref: "#/components/schemas/Accessibility"
        contributors:
          description: List of people contributing to the production, e.g. director(s), stage designer(s), musical director(s), etc.
          type: array
          items:
            $ref: "#/components/schemas/Person"
        performers:
          description: List of people performing in the production.
          type: array
          items:
            $ref: "#/components/schemas/Person"

    Event:
      type: object
      required:
        - startDate
      additionalProperties: false
      properties:
        startDate:
          type: string
          description: "The start date and time of the event (in ISO 8601 date format)."
          format: date-time
        endDate:
          type: string
          description: "The end date and time of the event (in ISO 8601 date format)."
          format: date-time
        duration:
          type: integer
          format: int64
          description: The duration of the event in minutes.
          example: 90
          minimum: 0
        # pause:
        #   type: boolean
        #   description: "TODO: Gibt es hierfür eine Entsprechung in schema.org?"
        #   example: false
        url:
          type: string
          description: Link to further information about the event
          format: uri
          example: "https://staatstheater-augsburg.de/hedwig_and_the_angry_inch"
        # inLanguage:
        #   type: string
        #   description: Primary language of the event
        #   format: can/should we make this an enum of language codes?
        
        location:
          description: Location where this event is happening.
          $ref: "#/components/schemas/Location"    
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"

    Offer:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          example: Normalpreis
          description: 'A descriptive name for this offer, e.g. "Normalpreis", "Ermäßigt", "Preisgruppe A", usw.'
        price:
          type: number
          format: float
          example: 25.50
          minimum: 0
        priceCurrency:
          type: string
          description: "The currency of the price. Use standard formats: TODO"
          example: EUR
        url:
          type: string
          description: Ticketing link of the event
          format: uri
          example: "https://webshop-tickets.staatstheater-augsburg.de/de/tickets/hedwig-and-the-angry-inch/brechtbuehne-im-gaswerk-14-12-2023-19-30"

    Person:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          description: The person's name
        role:
          type: string
          description: 'This person''s role in the production, e.g. "Regie" or "Dramaturgie". For performers, this should be the name of the role(s) they are performing.'

    Location:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          example: brechtbühne im Gaswerk
        postalCode:
          type: string
          example: 86156
          # pattern: "\d{5}"
        streetAddress:
          type: string
          example: Am Alten Gaswerk 7
        city:
          type: string
          example: Augsburg
        wheelChairPlaces:
          type: array
          description: Describes the presence of reserved spots for wheelchairs in this location, as defined by [a11yjson](https://sozialhelden.github.io/a11yjson/describing-objects/interfaces/#wheelchairplaces).
          items:
            $ref: "#/components/schemas/WheelChairPlace"

    Accessibility:
      type: object
      additionalProperties: false
      properties:
        accessModeSufficient:
          type: array
          items:
            type: string
            description: A list of single or combined accessModes that are sufficient to understand all the intellectual content of a resource.
            enum: [auditory, tactile, textual, visual]
        accessibilityHazard:
          type: array
          items:
            type: string
            example: flashingHazard,
            enum:
              [
                none,
                unknown,
                flashingHazard,
                motionSimulationHazard,
                soundHazard,
                noFlashingHazard,
                noMotionSimulationHazard,
                noSoundHazard,
                unknownFlashingHazard,
                unknownMotionSimulationHazard,
                unknownSoundHazard,
              ]
        accessibilitySummary:
          type: string
          description: A human-readable summary of specific accessibility features or deficiencies
          example: "Dieses Stück enthält Stroboskoplicht"

    WheelChairPlace:
      type: object
      additionalProperties: false
      description: Describes the presence of reserved spots for wheelchairs, as defined by [a11yjson](https://sozialhelden.github.io/a11yjson/describing-objects/interfaces/#wheelchairplaces).
      required:
        - count
      properties:
        count:
          type: integer
          example: 2
          description: The number of designated places for wheelchairs in this location.
        hasSpaceForAssistant:
          type: boolean
          description: Is there additional space for an assistant?
          example: false
        wheelchairUserCapacity:
          type: integer
          description: The number of people using a wheelchair that can be accomodated at the same time. Use this when there is no designated space for wheelchair users, but the number is known.
