openapi: 3.0.3
info:
  title: Use Case 3 - API
  description: |-
    ### WIP: This document is a work in progress. The API documented here is subject to change and should not be widely adopted yet.
    This document describes the public API implemented by theaters to provide their current repertoire.
    The data structure is based on [schema.org](https://schema.org) types, in particular [CreativeWork](https://schema.org/CreativeWork) and [Event](https://schema.org/Event).

    This document is intended as documentation for consumers of the API *as well as* anyone who intends to implement an API endpoint that is compatible with Use Case 3. 

    **Note for API implementors:** It's not required to use the same endpoint name as documented here. The important part is to implement a single endpoint that returns data in the format declared in this specification.

    ## Tools for API implementors
    To aid theaters implementing this API, we provide two tools:
    ### [Validator](validate)
    Use the [Validator](validate) to test whether your implementation matches the API specification.

    ### [Data Viewer](view)
    You can use the [Data Viewer](view) to display information from the API in a more human-friendly way.
    This can be helpful to quality control the data that is returned by your API implementation.
  # termsOfService: http://swagger.io/terms/
  contact:
    email: retzlaff@buehnenverein.de
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v2
# servers:
#   - url: https://petstore3.swagger.io/api/v3
tags:
  - name: events
    description: Endpoint providing public information about upcoming events
paths:
  /events:
    get:
      tags:
        - events
      summary: Provides public information about events
      description: "TODO: Write description"
      operationId: getEvents
      responses:
        "200":
          description: successful operation
          content:
            application/ld+json:
              schema:
                $ref: "./schemas/schema.yml"
