openapi: 3.0.3
info:
  title: Use Case 3 - API
  description: |-
    ### WIP: This document is a work in progress. The API documented here is subject to change and should not be widely adopted yet.
    This document describes the public API implemented by theaters to provide their current repertoire.

    This document is intended as documentation for consumers of the API *as well as* anyone who intends to implement an API endpoint that is compatible with Use Case 3. 

    ### Notes for API implementors

    * It's not required to use the same endpoint name as documented here. The important part is to implement a single endpoint that returns data in the format declared in this specification.
    * You can test whether your implementation matches this specification using our custom [validation page](validate)
  # termsOfService: http://swagger.io/terms/
  contact:
    email: retzlaff@buehnenverein.de
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
# servers:
#   - url: https://petstore3.swagger.io/api/v3
tags:
  - name: events
    description: Endpoint providing public information about upcoming events
paths:
  /events:
    get:
      tags:
        - events
      summary: Provides public information about events
      description: "TODO: Write description"
      operationId: getEvents
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repertoire"
components:
  schemas:
    Repertoire:
      $id: https://peret.github.io/uc3-openapi/schema.json
      required:
        - name
        - productions
        - version
      additionalProperties: false
      type: object
      properties:
        version:
          type: string
          description: The API version that is being used. MUST be the string "v1" for now.
          enum:
            - v1
        name:
          type: string
          description: "The organization's name"
          example: "Staatstheater Augsburg"
        address:
          type: object
          additionalProperties: false
          properties:
            postalCode:
              type: string
              # pattern: "\d{5}"
              example: 86153
            streetAddress:
              type: string
              example: Provinostr. 52
            city:
              type: string
              example: Augsburg
        productions:
          type: array
          description: "The collection of all productions in the repertoire."
          items:
            $ref: "#/components/schemas/Production"

    Production:
      type: object
      description: "An object containing unchanging information about the production."
      additionalProperties: false
      required:
        - title
        - events
      properties:
        title:
          type: string
          description: The event title
          example: Hedwig and the Angry Inch
        subtitle:
          type: string
          description: The event's optional subtitle
          example: US-amerikanisches Off-Broadway-Rock-Musical
        description:
          type: string
          description: A text describing the production
          example: Hedwig, die Queen des Glamrock, kommt auf ihrer Tournee in Augsburg vorbei! Gemeinsam mit ihrer Band The Angry Inch gibt sie eines ihrer mitreißenden Konzerte. Zwischen den Songs, die – mal Rocknummer, mal Country-Ballade – von ihrem Leben und der Suche nach der eigenen Identität erzählen, kommt sie dem Publikum so nah wie nie.\nDiese Show sollten Sie nicht verpassen!
        teaser:
          type: string
          description: A short text describing the production
          example: "Das Kult-Rockmusical »Hedwig and the Angry Inch« wurde innerhalb weniger Jahre vom Off-Broadway-Geheimtipp zu einem Hit am Broadway selbst. 2023 erobert Hedwig, die »weltweit ignorierte Queen of Glamrock« endlich auch die Herzen des Augsburger Publikums – mit dem langjährigen Schauspiel-Ensemble-Mitglied Thomas Prazak in der Hauptrolle. Die Live-Musik steuern Stefan Leibold, Jonas Horche, Tilman Herpichböhm und Niklas Rehle als Band »The Angry Inch« bei."
        additionalInfo:
          type: string
          description: Additional information about the production
        events:
          type: array
          description: "List of current events offered by the organization"
          items:
            $ref: "#/components/schemas/Event"
        genre:
          type: string
          description: The genre of this production. Must use one of the pre-defined values.
          enum:
            - audiowalk
            - ballett
            - digitaltheater
            - figurentheater
            - game-theater
            - hoerspiel
            - improtheater
            - installation
            - kabarett-comedy
            - kammerkonzert
            - konzert
            - lecture-performance
            - lesung
            - musical
            - musiktheater
            - objekttheater
            - oper
            - operette
            - performance
            - physical-theatre
            - podcast
            - puppentheater
            - sinfoniekonzert
            - sprechtheater
            - szenische-lesung
            - szenisches-konzert
            - tanz
            - theater-im-oeffentlichen-raum
            - workshop
            - zeitgenoessischer-tanz
          example: "Rock-Musical"
        accessibility:
          $ref: "#/components/schemas/Accessibility"
        participants:
          description: |-
            List of all people contributing to and participating in the production, e.g. directors, stage designers, musical directors, performers, etc.

            If multiple people perform the same role/function (e.g. there is multiple directors or multiple actors perform the same role on stage at the same time),
            each person should get their own entry in the `participants` array.
          type: array
          items:
            $ref: "#/components/schemas/Participant"

    Event:
      type: object
      required:
        - startDate
      additionalProperties: false
      properties:
        startDate:
          type: string
          description: "The start date and time of the event (in ISO 8601 date format)."
          format: date-time
        endDate:
          type: string
          description: "The end date and time of the event (in ISO 8601 date format)."
          format: date-time
        duration:
          type: integer
          format: int64
          description: The duration of the event in minutes.
          example: 90
          minimum: 0
        # pause:
        #   type: boolean
        #   description: "TODO: Gibt es hierfür eine Entsprechung in schema.org?"
        #   example: false
        url:
          type: string
          description: Link to further information about the event
          format: uri
          example: "https://staatstheater-augsburg.de/hedwig_and_the_angry_inch"
        # inLanguage:
        #   type: string
        #   description: Primary language of the event
        #   format: can/should we make this an enum of language codes?
        
        locations:
          description: The location of this event. An event can take place at one or more physical locations,
             one or more virtual locations, or both, if it's a hybrid event.
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/Location"    
              - $ref: "#/components/schemas/VirtualLocation"    
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"

    Offer:
      type: object
      additionalProperties: false
      required:
        - minPrice
        - priceCurrency
      properties:
        name:
          type: string
          example: Normalpreis
          description: 'A descriptive name for this offer, e.g. "Normalpreis", "Ermäßigt", "Preisgruppe A", usw.'
        minPrice:
          type: number
          description: The minimum price of this offer.
          format: float
          example: 25.50
          minimum: 0
        maxPrice:
          type: number
          description: The maximum price of this offer.
          format: float
          example: 45.50
          minimum: 0
        priceCurrency:
          type: string
          description: "The currency of the price. Use standard formats: TODO"
          example: EUR
        url:
          type: string
          description: Ticketing link for this offer
          format: uri
          example: "https://webshop-tickets.staatstheater-augsburg.de/de/tickets/hedwig-and-the-angry-inch/brechtbuehne-im-gaswerk-14-12-2023-19-30"

    Participant:
      type: object
      required:
        - names
      additionalProperties: false
      properties:
        function:
          type: string
          description:
            'This participant''s function in the production. Must use one of the pre-defined values.'
          # enum:
          #   - akrobatik
          #   - alles
          #   - assistenz
          #   - beratung
          #   - buehne
          #   - choreographie
          #   - clownerie
          #   - dramaturgie
          #   - expertin-des-alltags
          #   - fotografie
          #   - gebaerdensprache
          #   - gesang
          #   - grafik
          #   - inszenierung
          #   - jonglage
          #   - kamera-video
          #   - komposition
          #   - konzept
          #   - kostuem
          #   - kuenstlerische-leitung
          #   - licht
          #   - live-musik
          #   - marketing
          #   - maske
          #   - moderation
          #   - musik
          #   - musikalische-leitung
          #   - performance
          #   - produktion
          #   - programmierung
          #   - puppenbau
          #   - puppenspiel
          #   - regie
          #   - rigging
          #   - schauspiel
          #   - sound
          #   - tanz
          #   - technik
          #   - technische-leitung
          #   - text
          #   - ton
          #   - uebersetzung
          #   - vermittlung
          #   - virtual-reality-design
        roleName:
          type: string
          description: 'The name of the role(s) this participant is performing on stage, if any.'
        names:
          type: array
          items:
            type: string
          description:
            The name(s) of the person(s) performing this function/role. Must contain at least one name. Can contain multiple names, if multiple persons are
            performing the same role, but not at the same time.
          minItems: 1

    Location:
      type: object
      additionalProperties: false
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - Address
          description: The type of this location object. Must be "Address" for physical locations.
        name:
          type: string
          example: brechtbühne im Gaswerk
          description: The location's name
        postalCode:
          type: string
          example: 86156
          # pattern: "\d{5}"
          description: The location's postal code
        streetAddress:
          type: string
          example: Am Alten Gaswerk 7
          description: The location's street address
        city:
          type: string
          example: Augsburg
          description: The city the location is in
        wheelChairPlaces:
          type: object
          description: Describes the presence of reserved spots for wheelchairs in the location, as defined by [a11yjson](https://sozialhelden.github.io/a11yjson/describing-objects/interfaces/#wheelchairplaces).
          $ref: "#/components/schemas/WheelChairPlace"
        latitude:
          type: number
          description: "The location's latitude."
          minimum: -90
          maximum: 90
        longitude:
          type: number
          description: "The location's longitude."
          minimum: -180
          maximum: 180

    VirtualLocation:
      type: object
      additionalProperties: false
      description: The virtual location of an online or hybrid event
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - VirtualLocation
          description: The type of this location object. Must be "VirtualLocation" for virtual locations.
        name:
          type: string
          description:
            The virtual location's name
          example: Zoom
        url:
          type: string
          format: uri
          description: The event's URL, if this is an online or hybrid event
    Accessibility:
      type: object
      additionalProperties: false
      properties:
        accessModeSufficient:
          type: array
          items:
            type: string
            description: A list of single or combined accessModes that are sufficient to understand all the intellectual content of a resource.
            enum: [auditory, tactile, textual, visual]
        accessibilityHazard:
          type: array
          items:
            type: string
            example: flashingHazard,
            enum:
              - none
              - unknown
              - flashingHazard
              - motionSimulationHazard
              - soundHazard
              - noFlashingHazard
              - noMotionSimulationHazard
              - noSoundHazard
              - unknownFlashingHazard
              - unknownMotionSimulationHazard
              - unknownSoundHazard
        accessibilitySummary:
          type: string
          description: A human-readable summary of specific accessibility features or deficiencies of the production.
          example: "Dieses Stück enthält Stroboskoplicht"

    WheelChairPlace:
      type: object
      additionalProperties: false
      description: Describes the presence of reserved spots for wheelchairs, as defined by [a11yjson](https://sozialhelden.github.io/a11yjson/describing-objects/interfaces/#wheelchairplaces).
      required:
        - count
      properties:
        count:
          type: integer
          example: 2
          description: The number of designated places for wheelchairs in this location.
        hasSpaceForAssistant:
          type: boolean
          description: Is there additional space for an assistant?
          example: false
        wheelchairUserCapacity:
          type: integer
          description: The number of people using a wheelchair that can be accomodated at the same time. Use this when there is no designated space for wheelchair users, but the number is known.
